### ISSUE TITLE
Performance problem on large files/repositories

### ISSUE THREAD

**Issue by daanturo** [emacs-sideline/sideline-blame#3]
`sideline-blame`'s makes navigating some file laggy.

Example file: xdisp.c in Emacs's source code: https://github.com/emacs-mirror/emacs/blob/master/src/xdisp.c

The cursor is almost frozen when going around.

**Comment by jcs090218** [comment]
`sideline-blame` is using [vc-msg](https://github.com/redguardtoo/vc-msg) under the hood. You can try to report to the upstream, but I don't think there is space to improve the performance. 🤔

**Comment by daanturo** [comment]
To make it more responsive, currently I have this in my config to make the long synchronous call interruptible by keystrokes:

```elisp
(defun my-sideline-blame--get-message--make-interruptible-a (func &rest args)
  (-let* ((val
           (while-no-input
             (vector (apply func args)))))
    (cond
     ((vectorp val)
      (aref val 0))
     (:else
      ""))))

(advice-add
 #'sideline-blame--get-message
 :around #'my-sideline-blame--get-message--make-interruptible-a)
```

Maybe sideline-blame can incorporate something like `while-no-input` above? 

Under the hood, I guess the bottle neck is `vc-msg-git-shell-output`'s synchronous `shell-command-to-string` call. IMO the best solution should be using an asynchronous backend, but that requires too much work.

**Comment by jcs090218** [comment]
> Maybe sideline-blame can incorporate something like while-no-input above?

LGTM, would you like to make a PR for this? 🤔

> Under the hood, I guess the bottle neck is vc-msg-git-shell-output's synchronous shell-command-to-string call. IMO the best solution should be using an asynchronous backend, but that requires too much work.

Ideally, that's the best solution, especially on Windows.

**Comment by daanturo** [comment]
Silly me just found out that sideline.el fully supports async backends so I ended up writing a custom but git-only one. 😓
